//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tesst
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass1.
    /// </summary>
    // *** Start programmer edit section *** (NewClass1 CustomAttributes)

    // *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {

        // *** Start programmer edit section *** (NewClass1 CustomMembers)

        // *** End programmer edit section *** (NewClass1 CustomMembers)

    }
}

